import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';
import 'package:firebase_core/firebase_core.dart'; 
import 'firebase_options.dart';                     

// 💡 Change main() to an async function
void main() async {
  // 💡 1. Ensure Flutter framework engine components are fully bound before initializing plugins
  WidgetsFlutterBinding.ensureInitialized();
  
  // 💡 2. Initialize Firebase with the options generated by your CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Launch the app within Riverpod's ProviderScope
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: appRouter,
      title: 'Food App',
      theme: ThemeData(useMaterial3: true),
    );
  }
}